[build]
  publish = "public"
  command = "echo 'Static site build complete'"

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "netlify dev"
  port = 8888
